#!!!!! This file has been commited to source control and should not contain secure information
default: &DEFAULT
  
  email_user_name: 'none'    # Email server username
  email_password: 'none'                          # Email server password
  
  recaptcha_pub_key: 'GET_A_RECAPTCHA_KEY(TODO)'    # key available from http://recaptcha.net
  recaptcha_priv_key: 'GET_A_RECAPTCHA_KEY(TODO)'

  # keys
  hoptoad_key: '' # Get a hoptoad key - https://hoptoadapp.com/account/new

production:
  <<: *DEFAULT
  # Add production specific secrets
staging:
  <<: *DEFAULT
  # Add staging specific secrets
development:
  <<: *DEFAULT
  # Development specific secrets
test:
  <<: *DEFAULT
  # Test specific secrets
